apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend
  namespace: expense
data: 
  DB_HOST: {{ .Values.configMap.db_host }}
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels: 
    project: expense
    app: backend
    tier: backend
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: backend
      tier: backend
  template:
    metadata: 
      labels: 
        project: expense
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion}}"
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1 
kind: Service
metadata: 
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    app: backend
    tier: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuUtilization }}